name: jai_kisan
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


enable-experiment: super-parameters

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fading_edge_scrollview: ^4.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.0
  image_picker: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl:
  introduction_screen:
  google_fonts: 6.1.0
  lottie:
  geolocator:
  geocoding:
  
  google_sign_in: ^6.2.1
  provider:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  generate: true



    
