commodity_map = {
    'Pomegranate': 0,
    'Potato': 1,
    'Gur(Jaggery)': 2,
    'Peas(Dry)': 3,
    'Green Gram (Moong)(Whole)': 4,
    'Green Chilli': 5,
    'Taramira': 6,
    'Wood': 7,
    'Suvarna Gadde': 8,
    'Coconut': 9,
    'Black Gram (Urd Beans)(Whole)': 10,
    'Lime': 11,
    'Mango': 12,
    'Tobacco': 13,
    'Amla(Nelli Kai)': 14,
    'Brinjal': 15,
    'Jowar(Sorghum)': 16,
    'Karbuja(Musk Melon)': 17,
    'Sesamum(Sesame,Gingelly,Til)': 18,
    'Coconut Seed': 19,
    'Lentil (Masur)(Whole)': 20,
    'Bajra(Pearl Millet/Cumbu)': 21,
    'Water Melon': 22,
    'Surat Beans (Papadi)': 23,
    'Turnip': 24,
    'Niger Seed (Ramtil)': 25,
    'Rajgir': 26,
    'Snakeguard': 27,
    'Groundnut': 28,
    'Coriander(Leaves)': 29,
    'Cotton': 30,
    'Apple': 31,
    'Karamani': 32,
    'Sugar': 33,
    'Masur Dal': 34,
    'Peas Wet': 35,
    'Turmeric': 36,
    'Jute': 37,
    'Leafy Vegetable': 38,
    'Tamarind Fruit': 39,
    'Papaya': 40,
    'Papaya (Raw)': 41,
    'Broken Rice': 42,
    'Field Pea': 43,
    'Paddy(Dhan)(Common)': 44,
    'Elephant Yam (Suran)': 45,
    'Ginger(Dry)': 46,
    'Sponge gourd': 47,
    'Little gourd (Kundru)': 48,
    'Hybrid Cumbu': 49,
    'Round gourd': 50,
    'Banana - Green': 51,
    'Moath Dal': 52,
    'Duster Beans': 53,
    'Ashgourd': 54,
    'Peas cod': 55,
    'Arhar (Tur/Red Gram)(Whole)': 56,
    'Arhar Dal(Tur Dal)': 57,
    'Amphophalus': 58,
    'French Beans (Frasbean)': 59,
    'Long Melon(Kakri)': 60,
    'Capsicum': 61,
    'Garlic': 62,
    'Castor Seed': 63,
    'White Pumpkin': 64,
    'Grapes': 65,
    'Maize': 66,
    'Rice': 67,
    'Black Gram Dal (Urd Dal)': 68,
    'Chilly Capsicum': 69,
    'Squash(Chappal Kadoo)': 70,
    'Green Peas': 71,
    'Bitter gourd': 72,
    'Guar Seed(Cluster Beans Seed)': 73,
    'Green Avare (W)': 74,
    'Amaranthus': 75,
    'Pumpkin': 76,
    'Beans': 77,
    'Ridgeguard(Tori)': 78,
    'Cluster beans': 79,
    'Linseed': 80,
    'Arecanut(Betelnut/Supari)': 81,
    'Mango (Raw-Ripe)': 82,
    'Corriander seed': 83,
    'Pointed gourd (Parval)': 84,
    'Bengal Gram Dal (Chana Dal)': 85,
    'Cowpea (Lobia/Karamani)': 86,
    'Seemebadnekai': 87,
    'Wheat Atta': 88,
    'Kinnow': 89,
    'Tomato': 90,
    'Green Gram Dal (Moong Dal)': 91,
    'T.V. Cumbu': 92,
    'Mint(Pudina)': 93,
    'Soyabean': 94,
    'Ragi (Finger Millet)': 95,
    'Methi(Leaves)': 96,
    'Mousambi(Sweet Lime)': 97,
    'Drumstick': 98,
    'Tinda': 99,
    'Ber(Zizyphus/Borehannu)': 100,
    'Carrot': 101,
    'Knool Khol': 102,
    'Ground Nut Seed': 103,
    'Dry Chillies': 104,
    'Tapioca': 105,
    'Orange': 106,
    'Guar': 107,
    'Chikoos(Sapota)': 108,
    'Tender Coconut': 109,
    'Cucumbar(Kheera)': 110,
    'Paddy(Dhan)(Basmati)': 111,
    'Cowpea(Veg)': 112,
    'Plum': 113,
    'Lemon': 114,
    'Indian Beans (Seam)': 115,
    'Turmeric (raw)': 116,
    'Sweet Pumpkin': 117,
    'Mustard': 118,
    'Banana': 119,
    'Bhindi(Ladies Finger)': 120,
    'Kodo Millet(Varagu)': 121,
    'Cauliflower': 122,
    'Ginger(Green)': 123,
    'Wheat': 124,
    'Guava': 125,
    'Bottle gourd': 126,
    'Cabbage': 127,
    'Onion': 128,
    'Sweet Potato': 129,
    'Colacasia': 130,
    'Beetroot': 131,
    'Onion Green': 132,
    'Bengal Gram(Gram)(Whole)': 133,
    'Maida Atta': 134,
    'Kulthi(Horse Gram)': 135,
    'Pegeon Pea (Arhar Fali)': 136,
    'Gram Raw(Chholia)': 137,
    'Pineapple': 138,
    'Thinai (Italian Millet)': 139,
    'Raddish': 140,
    'Barley (Jau)': 141,
    'Spinach': 142,
    'Fish': 143
}
