state_mapping = {
    'Nagaland': 0,
    'Odisha': 1,
    'Punjab': 2,
    'Andhra Pradesh': 3,
    'Assam': 4,
    'Uttar Pradesh': 5,
    'Tripura': 6,
    'Tamil Nadu': 7,
    'Meghalaya': 8,
    'Kerala': 9,
    'Maharashtra': 10,
    'Himachal Pradesh': 11,
    'Jammu and Kashmir': 12,
    'Manipur': 13,
    'Telangana': 14,
    'Madhya Pradesh': 15,
    'Chhattisgarh': 16,
    'Gujarat': 17,
    'Uttarakhand': 18,
    'Rajasthan': 19,
    'Haryana': 20,
    'Karnataka': 21,
    'West Bengal': 22,
    'Pondicherry': 23,
    'Andaman and Nicobar': 24
}
