// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHPyJrRCyFyBPZBoom5lZdHxBZgRqfvic',
    appId: '1:914578047208:web:605fd009678c2dadcb495d',
    messagingSenderId: '914578047208',
    projectId: 'growgreen-2707b',
    authDomain: 'growgreen-2707b.firebaseapp.com',
    storageBucket: 'growgreen-2707b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9fv_X4h0BA_Td9LHV3fvBctCU3TA83uM',
    appId: '1:914578047208:android:71e09628baa084b7cb495d',
    messagingSenderId: '914578047208',
    projectId: 'growgreen-2707b',
    storageBucket: 'growgreen-2707b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4AwDKQm6dmffy7dSnZ4RofnGnprck_E',
    appId: '1:914578047208:ios:65f6e082a4e7d157cb495d',
    messagingSenderId: '914578047208',
    projectId: 'growgreen-2707b',
    storageBucket: 'growgreen-2707b.appspot.com',
    iosBundleId: 'com.example.vishnu',
  );
}
